version: 2

models:
  - name: stg_products
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: description
        tests:
          - not_null
  - name: stg_reviews
    columns:
      - name: product_id
        tests:
          - not_null
      - name: review
        tests:
          - not_null
