project:
  type: book
  output-dir: ../docs

book:
  title: "Modal Examples"
  author: "Ryan Wesslen"
  date: "6/15/2024"
  chapters:
    - index.qmd
    - 01_getting_started.qmd
    - 02_building_containers.qmd
    - 03_scaling_out.qmd
    - 04_secrets.qmd
    - 05_scheduling.qmd
    - 06_gpu_and_ml.qmd
  
bibliography: references.bib

format:
  html:
    theme: minty



