project:
  type: book
  output-dir: ../docs

book:
  title: "Modal Examples"
  author: "Ryan Wesslen"
  date: "6/19/2024"
  chapters:
    - index.qmd
    - 02_building_containers.qmd
    - 03_scaling_out.qmd
    - 04_secrets.qmd
    - 05_scheduling.qmd
    - 06_gpu_and_ml.qmd
    - 07_web_endpoints.qmd
    - 08_advanced.qmd
    - 09_job_queues.qmd
    - 10_integrations.qmd
    - 11_notebooks.qmd
    - 12_datasets.qmd
    - 13_finetuning.qmd
  
bibliography: references.bib

format:
  html:
    theme: minty
    embed-resources: false



